apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-name
spec:
  selector:
    matchLabels:
      app: hello-name
  template:
    metadata:
      labels:
        app: hello-name
    spec:
      containers:
      - image: nginx-skaffold
        name: hello-name

