apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: skaffold-ex
build:
  artifacts:
  - image: nginx-skaffold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-service.yaml
